package com.example.lightweaver.mobile.persistence.entities

data class DeviceAndTypeConfigurationEntity(val deviceConfiguration: DeviceConfigurationEntity, val typeConfiguration: DeviceTypeConfigurationEntity)